receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  isolationforest:
    forest_size: 100
    subsample_size: 256
    window_size: 1000
    contamination_rate: 0.10
    training_interval: 5m
    features: ["service.name"]

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    aggregation_cardinality_limit: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
    metrics_flush_interval: 15s
  servicegraph:
    store:
      ttl: 2s
      max_items: 1000

exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
  loki:
    endpoint: "http://victorialogs:9428/loki/api/v1/push"
  otlp/jaeger:
    endpoint: "http://victoriatraces:10428"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics, servicegraph]
      processors: [batch]
      exporters: [prometheusremotewrite, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, logging]
    traces:
      receivers: [otlp]
      processors: [isolationforest, batch]
      exporters: [spanmetrics, servicegraph, otlp/jaeger, logging]