apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true

  - name: VictoriaLogs
    type: loki
    access: proxy
    url: http://victorialogs:9428
    editable: true

  - name: VictoriaTraces
    type: tempo
    access: proxy
    url: http://victoriatraces:10428
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'VictoriaLogs'
      nodeGraph:
        enabled: true